In [10]:
import pandas as pd
detox_data = pd.read_csv('../data/raw/filtered.tsv', sep='\t', index_col=0)
detox_data

,reference,translation,similarity,lenght_diff,ref_tox,trn_tox
0,"If Alkar is flooding her with psychic waste, t...","if Alkar floods her with her mental waste, it ...",0.785171,0.010309,0.014195,0.981983
1,Now you're getting nasty.,you're becoming disgusting.,0.749687,0.071429,0.065473,0.999039
2,"Well, we could spare your life, for one.","well, we can spare your life.",0.919051,0.268293,0.213313,0.985068
3,"Ah! Monkey, you've got to snap out of it.","monkey, you have to wake up.",0.664333,0.309524,0.053362,0.994215
4,I've got orders to put her down.,I have orders to kill her.,0.726639,0.181818,0.009402,0.999348
...,...,...,...,...,...,...
577772,You didn't know that Estelle had stolen some f...,you didn't know that Estelle stole your fish f...,0.870322,0.030769,0.000121,0.949143
577773,It'il suck the life out of you!,you'd be sucked out of your life!,0.722897,0.058824,0.996124,0.215794
577774,"I can't fuckin' take that, bruv.",I really can't take this.,0.617511,0.212121,0.984538,0.000049
577775,They called me a fucking hero. The truth is I ...,"they said I was a hero, but I didn't care.",0.679613,0.358209,0.991945,0.000124
577776,I did not screw him.,I didn't fuck him.,0.868475,0.095238,0.009480,0.994174

In [11]:
detox_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 577777 entries, 0 to 577776
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   reference    577777 non-null  object
 1   translation  577777 non-null  object
 2   similarity   577777 non-null  float64
 3   lenght_diff  577777 non-null  float64
 4   ref_tox      577777 non-null  float64
 5   trn_tox      577777 non-null  float64
dtypes: float64(4), object(2)
memory usage: 30.9+ MB

In [12]:
detox_data = detox_data[detox_data['ref_tox'] >= detox_data['trn_tox']]
detox_data = detox_data.drop(columns=['similarity', 'lenght_diff', 'ref_tox', 'trn_tox'])
detox_data = detox_data.reset_index(drop=True)
detox_data

,reference,translation
0,I'm not gonna have a child... ...with the same...,I'm not going to breed kids with a genetic dis...
1,"They're all laughing at us, so we'll kick your...",they're laughing at us. We'll show you.
2,Maine was very short on black people back then.,there wasn't much black in Maine then.
3,"So now their spirits are cursed, walking back ...","their souls are cursed, they guard the paths, ..."
4,"Come on, Cal, leave that shit alone.","come on, Cal, put it down."
...,...,...
319137,I am so crazy nuts about you guys.,I'm so crazy about you guys.
319138,"I thought American men were bad enough, but no...","an American man is worth nothing, but for you,..."
319139,It'il suck the life out of you!,you'd be sucked out of your life!
319140,"I can't fuckin' take that, bruv.",I really can't take this.
319141,They called me a fucking hero. The truth is I ...,"they said I was a hero, but I didn't care."

In [13]:
paradetox_data = pd.read_csv('../data/external/paradetox.tsv', sep='\t')

paradetox_data.head(5)

,toxic,neutral1,neutral2,neutral3
0,he had steel balls too !,he was brave too!,NaN,NaN
1,"dude should have been taken to api , he would ...",It would have been good if he went to api. He ...,NaN,NaN
2,"im not gonna sell the fucking picture , i just...","I'm not gonna sell the picture, i just want to...",NaN,NaN
3,the garbage that is being created by cnn and o...,the news that is being created by cnn and othe...,The news that is being created by cnn and othe...,the garbage that is being created by cnn and o...
4,the reason they dont exist is because neither ...,The reason they don't exist is because neither...,NaN,NaN

In [14]:
paradetox_data = paradetox_data.drop(columns=paradetox_data.columns.values[2:])
paradetox_data.columns = detox_data.columns.values
paradetox_data

,reference,translation
0,he had steel balls too !,he was brave too!
1,"dude should have been taken to api , he would ...",It would have been good if he went to api. He ...
2,"im not gonna sell the fucking picture , i just...","I'm not gonna sell the picture, i just want to..."
3,the garbage that is being created by cnn and o...,the news that is being created by cnn and othe...
4,the reason they dont exist is because neither ...,The reason they don't exist is because neither...
...,...,...
11922,"this is the "" dumb "" shit they 're laughing at","this is the "" nonsense "" situation they 're la..."
11923,no seriously you 're fucking retarded,no seriously you 're slow..
11924,christians love to shit on the pope .,christians love to criticize the pope
11925,"but if saying "" fuck that group "" is much more...","but if saying"" that group is bad"" is much more..."
11926,shit we probably literally blow that up in a w...,We probably litteralky blow that up in a week.

In [15]:
data = pd.concat([detox_data, paradetox_data], ignore_index=True)
data

,reference,translation
0,I'm not gonna have a child... ...with the same...,I'm not going to breed kids with a genetic dis...
1,"They're all laughing at us, so we'll kick your...",they're laughing at us. We'll show you.
2,Maine was very short on black people back then.,there wasn't much black in Maine then.
3,"So now their spirits are cursed, walking back ...","their souls are cursed, they guard the paths, ..."
4,"Come on, Cal, leave that shit alone.","come on, Cal, put it down."
...,...,...
331064,"this is the "" dumb "" shit they 're laughing at","this is the "" nonsense "" situation they 're la..."
331065,no seriously you 're fucking retarded,no seriously you 're slow..
331066,christians love to shit on the pope .,christians love to criticize the pope
331067,"but if saying "" fuck that group "" is much more...","but if saying"" that group is bad"" is much more..."
331068,shit we probably literally blow that up in a w...,We probably litteralky blow that up in a week.

In [16]:
from sklearn.model_selection import train_test_split
train_data, test_data = train_test_split(data, test_size=0.2, random_state=42)
train_data

,reference,translation
135300,"Shit, and here I thought this guy talked with ...","hell, I thought this guy was talking to elves ..."
290297,I hate God-freaks.,I hate fanatics.
46621,"""Yeah, yeah, witness testimony is a bitch,"" Ze...","""yeah, yeah, the witness statements are really..."
47025,I wouldn't dance with him for all of Derbyshir...,"I wouldn't dance with him even for Derbyshire,..."
63161,"Look, let's just sell this shit.",we'll just sell it.
...,...,...
119879,But I am not lying when I say I've never had s...,but I didn't lie about having sex with Ricky.
259178,Dave Duncan killed my husband with a railroad ...,Dave Duncan rammed my husband's railway nail i...
131932,Otherwise Mother's arse would be dusting the f...,"otherwise, the mother would have cleaned the f..."
146867,Kill 'em before they could grow up and do the ...,killed before he could grow up and the same th...
121958,"You have to take a bath, stubborn!",you have to take a bath!

In [17]:
test_data

,reference,translation
174957,G...! What the fuck?,what is this?
320132,i think any one of any party who hides from th...,i think any one of any party who hides from th...
316823,We can have sex on the beach.,we can make love at the beach.
58017,Steele decided his only hope lay in playing dead.,his only hope was to pretend he was dead.
187929,He'il die before they get him to a surgeon.,he'll be gone before he gets to the surgeon.
...,...,...
5250,Don't fuck around!,don't bother!
114700,"Before the door in the face, before you nearly...",before you hit me in front of me before you al...
212784,Three thousand Negroes with ideas in their hea...,three thousand black men with ideas in their h...
9048,Drop the damn weapon!,drop the gun!
279789,"Ask me, you did the world a favor, ridding it ...",I think you did a favor for the world when you...

In [18]:
train_data.to_csv('../data/interim/train_filtered.csv')
test_data.to_csv('../data/interim/test_filtered.csv')